### ISSUE TITLE
Expiry certificate validation is failed. 

### ISSUE THREAD

**Issue by perneninag** [OxalisCommunity/commons-certvalidator#6] opened 2024-12-16 08:41 UTC
I couldn't validate revoked certificate when testing TC2A.4: Invalid certificate handling. I have used below config and placed all files in respective folders along with other config. But outbound still sending the document.

mode.default.security.validator = {
    class: network.oxalis.vefa.peppol.security.util.DifiCertificateValidator
    ALL: default
    AP: AP
    SMP: SMP
}

mode.TEST.security.pki = /pki/peppol-test.xml
mode.TEST.security.truststore.ap = /truststore/peppol-test-ap.jks
mode.TEST.security.truststore.smp = /truststore/peppol-test-smp.jks
mode.TEST.security.truststore.password = changeit

<img width="959" alt="image" src="https://github.com/user-attachments/assets/b36c0288-b9d3-4007-871a-14a504f09d13" />

**Comment by aaron-kumar** [comment] 2024-12-16 10:48
@perneninag: Please avoid posting same problem that you are facing at multiple places. 
If you are unsure about the resolution of problem that you are facing, first check closed issues and then in discussion channels of Oxalis, Oxalis-AS4 or Oxalis-NG repositories.

Closing this as duplicate of https://github.com/OxalisCommunity/oxalis-ng/discussions/3

PS: If you need extended support from the community of Peppol certified AP Oxalis users then please join Oxalis Membership.

**Closed by aaron-kumar** 2024-12-16 10:48 UTC
